name: laboratorio_digital
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.3
  file_picker: ^8.1.2
  flutter_math_fork: ^0.7.2
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.6+2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  flutter_pdf_text: ^0.9.0
  intl: ^0.19.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.4
  device_info_plus: ^9.1.2
  math_expressions: ^2.4.0
  image: ^4.2.0
  markdown_widget: ^2.3.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/Logo.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true